#!/bin/bash

echo "Look for directory $1 and change directory"

find ~/Documents/ -iname $1 -type d | xclip
pathcd=`xclip -o`

#~ echo $pathcd

path1=""
charac1="/"

let "a=0"
let "b=0"
    
for i in $pathcd; do
    if [ ${i:0:1} == "/" ] && [ "${a}" -eq "${b}" ];
    then
        path1="${path1} ${i}"
        let "a=a+1"
    elif [ ${i:0:1} != "/" ];
    then
        path1="${path1} ${i}"
    elif [ ${i:0:1} == "/" ] && [ "${a}" -ne "${b}" ];
    then
        echo $path1
        path1=""
        path1="${path1}${i}"
    fi
done



#~ echo $path1

#~ cd $pathcd
